version: 0.0
os: linux
files:
  - source: / # 인스턴스에 복사할 S3 파일의 경로, / 로 설정하면S3_BUCKET_NAME/PROJECT_NAME/GITHUB_SHA.zip
    destination: /home/ubuntu/duaily-server/ # 프로젝트 이름  # S3에서 가져온 파일을 저장할 위치
    overwrite: yes # 덮어쓰기 허용


permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/execute.sh
      timeout: 600 # 실행 타임아웃. 최대 3600초
      runas: ubuntu # 스크립트 실행 시 가장하는 사용자