version: '3'
services:
  redis:
    container_name: redis_test
    image: redis:latest
    ports:
      - "6376:6379"
    networks:
      - db_network

  mysql:
    container_name: mysql_test
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pw
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3303:3306"
    networks:
      - db_network


networks:
  db_network:
    driver: bridge