spring:
  application:
    name: jhouse-server

  profiles:
    include:
      secret

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ENC(1r+PBQMs51lTSvcS47i8+ncEVMvbrng8XhrHtwmiE6JeQVm/Q07WLQ5HHOY5PCQFOBzWaZIoE4kxIKJJ0Wm366UrXRXmFued3NhOI7iE006ufGGEAGulRQ==)
    username: ENC(Ft4VANPXNWbUqnXvim/g4w==)
    password: ENC(35dJqCmjA0lYMfEv1EiKPw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(Ua8NlOJqsCrv4+xRi1yNfg==)
    port: 6379

  mvc:
    path match:
      matching-strategy: ant_path_matcher
---
spring:
  profiles:
    active: dev

---
spring:
  profiles:
    active: prod
