spring:
  application:
    name: jhouse-server

  profiles:
    include:
      secret

  # 방금 추가한 부분
  cache:
    type: redis
    redis:
      cache-null-values: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        metadata_builder_contributor: com.example.jhouse_server.global.util.SqlFunctionsMetadataBuilderContributor
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ENC(XxBf/3kChMwGNU8+3ch/K9QXB4sRQ+WcSc94MOQqvBHS9lE9gYOA482/JSp4VvsrgQKMV8FLwZeFgGyMFk36B9cNJtFOKFr7hJ0Fowlk/QYjrW0dWJXsVg==)
    username: ENC(Ft4VANPXNWbUqnXvim/g4w==)
    password: ENC(35dJqCmjA0lYMfEv1EiKPw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(qtWZf5Lsfs8g2SGUf0xUhvT8gZgN7Wx3)
    port: 6376

  mvc:
    path match:
      matching-strategy: ant_path_matcher
    view:
      prefix: /templates/
      suffix: .html

  jwt:
    key: ENC(QN9igaTGD9IR2xKYJsA4sUc5a6rvaOdgN7IU1LtrazB51S1oGXb/z7JlDfOg325iIQGsNb7yFZX6oT2wW4+C9Swza7yvorcnwtrGExIVgrlq65Al/+egt2fAkHI79YNoWYRwPI4Br0o=)
  level:


cool:
  sms:
    api-key: ENC(65nOezIWpb58mF23J0oYUeXJMJ/iAsOVmP6dEFNjvdM=)
    api-secret: ENC(l1mqdDlmADtW1E3hb0+jkf/5CWNQg6r8yA5tRdO8ihQXZ9KIs9ReP5Mx1J2lG3T7)
    from: ENC(KdUMxAXBQVgK1ZjWJvvZpP1ZXZOaAVJ4)

aes:
  secret:
    key: ENC(+D1OqctErx4y5y6alEDE+KonIVum/jYCZ7hnMoeJinlljjvGVte0lXjx6h/qI6+H)
    alg: ENC(4EeK8heADvYLa0YJKYym/WkRLZjoea20neyqxvzPLiw=)

server:
  servlet:
    session:
      tracking-modes: cookie

#logging:
#  config: classpath:logback-spring.xml

