spring:
  application:
    name: jhouse-server

  profiles:
    include:
      secret

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        metadata_builder_contributor: com.example.jhouse_server.global.util.SqlFunctionsMetadataBuilderContributor
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ENC(XxBf/3kChMwGNU8+3ch/K9QXB4sRQ+WcSc94MOQqvBHS9lE9gYOA482/JSp4VvsrgQKMV8FLwZeFgGyMFk36B9cNJtFOKFr7hJ0Fowlk/QYjrW0dWJXsVg==)
    username: ENC(Ft4VANPXNWbUqnXvim/g4w==)
    password: ENC(35dJqCmjA0lYMfEv1EiKPw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(qtWZf5Lsfs8g2SGUf0xUhvT8gZgN7Wx3)
    port: 6379

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jwt:
    key: ENC(QN9igaTGD9IR2xKYJsA4sUc5a6rvaOdgN7IU1LtrazB51S1oGXb/z7JlDfOg325iIQGsNb7yFZX6oT2wW4+C9Swza7yvorcnwtrGExIVgrlq65Al/+egt2fAkHI79YNoWYRwPI4Br0o=)

cool:
  sms:
    api-key: ENC(65nOezIWpb58mF23J0oYUeXJMJ/iAsOVmP6dEFNjvdM=)
    api-secret: ENC(l1mqdDlmADtW1E3hb0+jkf/5CWNQg6r8yA5tRdO8ihQXZ9KIs9ReP5Mx1J2lG3T7)
    from: ENC(KdUMxAXBQVgK1ZjWJvvZpP1ZXZOaAVJ4)

#—
#spring:
#  profiles:
#    active: prod
