spring:
  application:
    name: jhouse-prod

  config:
    activate:
      on-profile: "prod"

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ENC(jHn8mCpeceVJdoywHaYNsz3LN9K1FmTg8G6UlCUJ8tm/ynVfbRKQKwE1ULOjLAN6/A0xuZed4cIBMsgkthdDYOsb+u9LZHr5eCM6aJdlXRBZGjz8+Usb6rw8XAeSY3vSwshDyXvrPkH7tksKwDAs9TbFUxlmt1ZyzUef9RwH1u0=)
    username: ENC(xvhrw7GfC3KXyEKIbbXRLA==)
    password: ENC(vJiB+8VMlNd15HOYQaBDZKNBBO5rHvrY)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(Ua8NlOJqsCrv4+xRi1yNfg==)
    port: 6379

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jwt:
    key: ENC(QN9igaTGD9IR2xKYJsA4sUc5a6rvaOdgN7IU1LtrazB51S1oGXb/z7JlDfOg325iIQGsNb7yFZX6oT2wW4+C9Swza7yvorcnwtrGExIVgrlq65Al/+egt2fAkHI79YNoWYRwPI4Br0o=)

cool:
  sms:
    api-key: ENC(65nOezIWpb58mF23J0oYUeXJMJ/iAsOVmP6dEFNjvdM=)
    api-secret: ENC(l1mqdDlmADtW1E3hb0+jkf/5CWNQg6r8yA5tRdO8ihQXZ9KIs9ReP5Mx1J2lG3T7)
    from: ENC(KdUMxAXBQVgK1ZjWJvvZpP1ZXZOaAVJ4)