spring:
  application:
    name: jhouse-server

  profiles:
    include:
      secret

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: ENC(XxBf/3kChMwGNU8+3ch/K9QXB4sRQ+WcSc94MOQqvBHS9lE9gYOA482/JSp4VvsrgQKMV8FLwZeFgGyMFk36B9cNJtFOKFr7hJ0Fowlk/QYjrW0dWJXsVg==)
    username: ENC(Ft4VANPXNWbUqnXvim/g4w==)
    password: ENC(35dJqCmjA0lYMfEv1EiKPw==)
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ENC(Ua8NlOJqsCrv4+xRi1yNfg==)
    port: 6376

  mvc:
    path match:
      matching-strategy: ant_path_matcher
#---
#spring:
#  profiles:
#    active: prod
