name: "[운영] 헬스체크"

on:
  pull_request:
    branches:
      - chore/infra
  workflow_dispatch:

jobs:
  healthcheck:
    runs-on: ubuntu-latest
    steps:
      - name: 유저 API Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: ${{ secrets.BASE_URI_PROD }}
          max-attempts: 3
          retry-delay: 1s

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROD }} # required
        if: always() # Pick up events even if the job fails or is canceled.


